name: Deploy Node.js Backend to UAT via SSM

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Run backend deployment commands via SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying backend via GitHub Actions" \
            --parameters 'commands=["cd /home/ubuntu/sample_nodejs", "git pull origin main", "npm install", "pm2 restart 1"]' \
            --region ${{ vars.AWS_REGION }}
